services:
    _defaults:
        autowire:      true
        autoconfigure: true

    Psr\Log\LoggerInterface:
        alias: monolog.logger.contao

    HeimrichHannot\ResourceBookingBundle\:
        resource: ../src
        exclude:
            - ../src/{Contao,ContaoManager,DependencyInjection,Event,Exception,Model,Widget}
            - ../src/Booking/*.php
            - ../src/Booking/Payload/BookingPayload.php
